#!/usr/bin/env sh
# assemble-aeo-bundle.sh OS ARCH — build the aeo CLI release bundle for a target.
#
# Produces dist/aeo-<os>-<arch>.tar.gz from an ALREADY-BUILT bin/aeo (the caller,
# release-aeo.yml, cross-builds bin/aeo first). Bundle layout:
#
#   aeo-<os>-<arch>/
#     bin/aeo                       the target-native CLI
#     Makefile                      the install target
#     install.sh                    runs `make -C share/aeo install PREFIX=…`
#     share/aeo/bin/aeo             (the CLI again — the wrapper execs this)
#     share/aeo/lib/                the runtime module tree
#     share/aeo/examples/           the substrate-grid examples
#
# Factored out of the workflow so it's testable locally:
#   ae build bin/aeo.ae -o bin/aeo --lib lib
#   sh .github/scripts/assemble-aeo-bundle.sh linux x86_64
#   tar tzf dist/aeo-linux-x86_64.tar.gz | head
set -eu

OS="${1:?usage: assemble-aeo-bundle.sh OS ARCH}"
ARCH="${2:?usage: assemble-aeo-bundle.sh OS ARCH}"
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

[ -x bin/aeo ] || { echo "assemble: bin/aeo not built — run 'ae build bin/aeo.ae -o bin/aeo --lib lib' first" >&2; exit 1; }

BASE="aeo-$OS-$ARCH"
STAGE="dist/$BASE"
rm -rf "$STAGE"
mkdir -p "$STAGE/bin" "$STAGE/share/aeo/bin"

# The CLI, at the bundle root (for direct use) and under share/ (what the
# installed wrapper execs).
cp -f bin/aeo "$STAGE/bin/aeo"
cp -f bin/aeo "$STAGE/share/aeo/bin/aeo"
chmod +x "$STAGE/bin/aeo" "$STAGE/share/aeo/bin/aeo"

# The runtime tree the CLI needs at AEO_HOME: lib/ (staged into every build) and
# examples/ (the substrate grid). NOT test/ — a release ships no test harness.
cp -R lib "$STAGE/share/aeo/lib"
[ -d examples ] && cp -R examples "$STAGE/share/aeo/examples" || true

# Ship VERSION (if present) so the installed stamp reads clean.
[ -f VERSION ] && cp -f VERSION "$STAGE/share/aeo/VERSION" || true

# The bundled installer is COPY-ONLY — NO `make`. bin/aeo is already the
# target-native binary and the tree needs no compilation, so installing is a
# copy + a wrapper. This deliberately does NOT run `make -C share/aeo install`:
# that would (a) require GNU make on the target — a virginal debian-slim / bare
# VM has none, giving the bogus "GNU make is required" failure a prebuilt
# install exists to avoid — and (b) the Makefile's install rebuilds bin/aeo via
# `ae`, clobbering the cross-built binary and needing `ae` at install time.
# We reproduce make install's COPY PHASE directly. (Byte-for-byte the aeb fix,
# aeb commit 87a30b8.)
cat > "$STAGE/install.sh" <<'EOF'
#!/bin/sh
# Install this prebuilt aeo bundle. No compiler, no `make`: bin/aeo is already
# target-native and the runtime tree needs no build — installing is a copy plus
# a wrapper. Usage: ./install.sh [PREFIX]   (default: ~/.local)
set -eu
here="$(cd "$(dirname "$0")" && pwd)"
src="$here/share/aeo"
PREFIX="${1:-$HOME/.local}"
BINDIR="$PREFIX/bin"
SHAREDIR="$PREFIX/share/aeo"

mkdir -p "$BINDIR" "$SHAREDIR" "$SHAREDIR/bin"
# Clear any prior install so no stale files linger, then copy the tree.
rm -f "$BINDIR/aeo"
rm -rf "$SHAREDIR/lib" "$SHAREDIR/examples" "$SHAREDIR/bin/aeo"
cp -f "$src/bin/aeo" "$SHAREDIR/bin/aeo"; chmod +x "$SHAREDIR/bin/aeo"
cp -R "$src/lib" "$SHAREDIR/lib"
[ -d "$src/examples" ] && cp -R "$src/examples" "$SHAREDIR/examples" || true
[ -f "$src/VERSION" ] && cp -f "$src/VERSION" "$SHAREDIR/VERSION" || true

# The $BINDIR/aeo wrapper: pin AEO_HOME at the installed runtime, exec the CLI.
# Byte-for-byte what the Makefile's `install` writes.
printf '%s\n' \
    '#!/usr/bin/env bash' \
    '# aeo wrapper — generated by the prebuilt-bundle install.sh' \
    "export AEO_HOME=\"$SHAREDIR\"" \
    "exec \"$SHAREDIR/bin/aeo\" \"\$@\"" \
    > "$BINDIR/aeo"
chmod +x "$BINDIR/aeo"

# Stamp so `aeo`'s install tree reads clean rather than "un-installed".
VER="$( [ -f "$src/VERSION" ] && tr -d '[:space:]' < "$src/VERSION" || echo 0.0.0 )"
printf 'installed %s\nversion %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$VER" \
    > "$SHAREDIR/AEO_STAMP"

echo "aeo installed to $BINDIR/aeo (AEO_HOME=$SHAREDIR)"
echo "NOTE: aeo shells 'ae' at runtime — ensure the Aether toolchain is on PATH."
EOF
chmod +x "$STAGE/install.sh"

# Archive: tar.gz (+ .sha256 is done by the caller's Checksum step). zip too, so
# a minimal box with only tar OR unzip can extract (matches aeb's dual-format).
( cd dist && tar -czf "$BASE.tar.gz" "$BASE" )
if command -v zip >/dev/null 2>&1; then
    ( cd dist && zip -qr "$BASE.zip" "$BASE" )
fi

echo "assembled: dist/$BASE.tar.gz"
tar -tzf "dist/$BASE.tar.gz" | sed 's/^/  /' | head -20
