# aeo Makefile
#
# The `aeo` CLI is built by `ae build bin/aeo.ae` and, UNLIKE aeo-agent, is NOT
# self-contained: at runtime it reads AEO_HOME to find lib/ (it cp's $AEO_HOME/lib
# into every composition build) and shells `ae` to compile. So an install must
# lay down the runtime tree (bin/aeo + lib/ + examples/) and put a wrapper on
# PATH that pins AEO_HOME at the installed copy. Pattern mirrors aeb's Makefile:
# `make install` copies to $PREFIX/share/aeo and generates $PREFIX/bin/aeo.
#
# Two entry paths both use this:
#   - from a clone:   `make install`  (build the CLI if needed, then install)
#   - from a release bundle: the bundle's install.sh runs `make -C share/aeo
#     install PREFIX=…` against an ALREADY-BUILT bin/aeo (no `ae` needed) — see
#     BUILT_AEO below, which skips the build when bin/aeo already exists.

AETHER  ?= ae
PREFIX   ?= $(HOME)/.local
BINDIR   ?= $(PREFIX)/bin
SHAREDIR ?= $(PREFIX)/share/aeo

# Source-content hash of the aeo tree — a stable identity for the stale-install
# check (content, not mtime: a revert restores the prior hash). git ls-files
# covers tracked sources; find is the outside-a-checkout fallback.
SRCHASH_CMD = { git ls-files bin lib 2>/dev/null | grep . || find bin lib -type f; } | LC_ALL=C sort | xargs sha256sum 2>/dev/null | sha256sum | cut -c1-12

.PHONY: all build install uninstall clean check-install

all: build

# build — compile the aeo CLI to bin/aeo. Idempotent-ish: ae's own content hash
# skips recompiles when nothing changed. Needs `ae` on PATH.
build:
	$(AETHER) build bin/aeo.ae -o bin/aeo --lib lib

# install — copy the runtime tree to $(SHAREDIR) and drop a wrapper at
# $(BINDIR)/aeo that pins AEO_HOME at the installed copy. The wrapper is
# regenerated each install so PREFIX changes are picked up.
#
# bin/aeo must exist first. From a clone that means `make build` (or `make
# install` depends on it); from a release bundle bin/aeo is already the shipped,
# target-native binary — so we DON'T force a rebuild here (the bundle box may
# have no `ae`). Build only if the binary is absent.
install:
	@[ -x bin/aeo ] || { echo "bin/aeo not built — running 'make build'"; $(MAKE) build; }
	@mkdir -p $(BINDIR) $(SHAREDIR) $(SHAREDIR)/bin
	rm -f $(BINDIR)/aeo
	rm -rf $(SHAREDIR)/lib $(SHAREDIR)/examples $(SHAREDIR)/bin/aeo
	cp -f bin/aeo $(SHAREDIR)/bin/aeo
	chmod +x $(SHAREDIR)/bin/aeo
	cp -R lib $(SHAREDIR)/lib
	@[ -d examples ] && cp -R examples $(SHAREDIR)/examples || true
	@printf '%s\n' \
	    '#!/usr/bin/env bash' \
	    '# aeo wrapper — generated by aeo `make install`' \
	    'export AEO_HOME="$(SHAREDIR)"' \
	    'exec "$(SHAREDIR)/bin/aeo" "$$@"' \
	    > $(BINDIR)/aeo
	chmod +x $(BINDIR)/aeo
	@SRCH=$$( $(SRCHASH_CMD) ); \
	 GITD=$$(git describe --always --dirty 2>/dev/null || echo unknown); \
	 VER=$$( [ -f VERSION ] && tr -d '[:space:]' < VERSION || echo 0.0.0-dev+$$SRCH ); \
	 printf 'src %s\ncommit %s\ninstalled %s\ntoolchain %s\nversion %s\n' \
	    "$$SRCH" "$$GITD" "$$(date '+%Y-%m-%d %H:%M:%S')" "$$($(AETHER) --version 2>/dev/null | head -1)" "$$VER" \
	    > $(SHAREDIR)/AEO_STAMP; \
	 echo "installed:"; \
	 echo "  wrapper:  $(BINDIR)/aeo   (pins AEO_HOME=$(SHAREDIR))"; \
	 echo "  runtime:  $(SHAREDIR)/"; \
	 echo "  version:  aeo $$VER (git $$GITD)"; \
	 echo "  NOTE: aeo shells 'ae' at runtime — ensure the Aether toolchain is on PATH."

uninstall:
	rm -f $(BINDIR)/aeo
	rm -rf $(SHAREDIR)

clean:
	rm -f bin/aeo

# check-install — is the installed aeo current with this source tree? Compares
# the dev tree's source-content hash against the installed AEO_STAMP.
check-install:
	@if [ ! -f "$(SHAREDIR)/AEO_STAMP" ]; then \
	    echo "aeo: not installed at $(SHAREDIR) — run 'make install'"; \
	else \
	    dev=$$( $(SRCHASH_CMD) ); \
	    inst=$$(awk '$$1=="src"{print $$2}' "$(SHAREDIR)/AEO_STAMP"); \
	    if [ "$$dev" = "$$inst" ]; then \
	        echo "aeo: installed tree is current (src $$inst)"; \
	    else \
	        echo "aeo: installed tree is STALE — installed src $$inst, this tree $$dev — run 'make install'"; \
	    fi; \
	fi
