# aeo Makefile
#
# The `aeo` CLI is built by `ae build bin/aeo.ae` and, UNLIKE aeo-agent, is NOT
# self-contained: at runtime it reads AEO_HOME to find lib/ (it cp's $AEO_HOME/lib
# into every composition build) and shells `ae` to compile. So an install must
# lay down the runtime tree (bin/aeo + lib/ + examples/) and put a wrapper on
# PATH that pins AEO_HOME at the installed copy. Pattern mirrors aeb's Makefile:
# `make install` copies to $PREFIX/share/aeo and generates $PREFIX/bin/aeo.
#
# Two entry paths both use this:
#   - from a clone:   `make install`  (build the CLI if needed, then install)
#   - from a release bundle: the bundle's install.sh runs `make -C share/aeo
#     install PREFIX=…` against an ALREADY-BUILT bin/aeo (no `ae` needed) — see
#     BUILT_AEO below, which skips the build when bin/aeo already exists.

AETHER  ?= ae
PREFIX   ?= $(HOME)/.local
BINDIR   ?= $(PREFIX)/bin
SHAREDIR ?= $(PREFIX)/share/aeo

# Source-content hash of the aeo tree — a stable identity for the stale-install
# check (content, not mtime: a revert restores the prior hash). git ls-files
# covers tracked sources; find is the outside-a-checkout fallback.
SRCHASH_CMD = { git ls-files bin lib 2>/dev/null | grep . || find bin lib -type f; } | LC_ALL=C sort | xargs sha256sum 2>/dev/null | sha256sum | cut -c1-12

.PHONY: all build install uninstall clean check-install

all: build

# build — compile the aeo CLI to bin/aeo. Idempotent-ish: ae's own content hash
# skips recompiles when nothing changed. Needs `ae` on PATH.
build:
	$(AETHER) build bin/aeo.ae -o bin/aeo --lib lib

# bin/aeo — a TIMESTAMP rule so a clone install rebuilds the front-door whenever
# the SOURCE (bin/aeo.ae or anything under lib/) is newer than the built binary.
# This is the fix for a nasty footgun: `git pull` changing bin/aeo.ae used to
# leave a stale bin/aeo in place (the old guard was just `[ -x bin/aeo ]`), so
# `make install` would ship a front-door that lagged the runner — the two are
# separate artifacts and only the runner recompiles at `aeo up`. A stale
# front-door silently mis-passed parameters to the current runner (see item 6).
# Guarded on `ae` being present so a release-bundle box (prebuilt bin/aeo, no
# toolchain) never tries to rebuild — there the shipped binary is authoritative
# and, being newer-on-unpack, won't trip this rule anyway.
bin/aeo: bin/aeo.ae $(shell find lib -type f 2>/dev/null)
	@if command -v $(AETHER) >/dev/null 2>&1; then \
	    echo "bin/aeo is stale (source newer) — rebuilding"; \
	    $(AETHER) build bin/aeo.ae -o bin/aeo --lib lib; \
	    touch bin/aeo; \
	else \
	    echo "NOTE: $(AETHER) not on PATH — using the existing prebuilt bin/aeo (bundle install)"; \
	fi

# install — copy the runtime tree to $(SHAREDIR) and drop a wrapper at
# $(BINDIR)/aeo that pins AEO_HOME at the installed copy. The wrapper is
# regenerated each install so PREFIX changes are picked up.
#
# Depends on the bin/aeo timestamp rule above: from a clone, a source change
# forces a front-door rebuild BEFORE the copy (no more stale-front-door footgun);
# from a release bundle (no `ae`), the prebuilt bin/aeo is used as-is.
install: bin/aeo
	@mkdir -p $(BINDIR) $(SHAREDIR) $(SHAREDIR)/bin
	rm -f $(BINDIR)/aeo
	rm -rf $(SHAREDIR)/lib $(SHAREDIR)/examples $(SHAREDIR)/bin/aeo
	cp -f bin/aeo $(SHAREDIR)/bin/aeo
	chmod +x $(SHAREDIR)/bin/aeo
	cp -R lib $(SHAREDIR)/lib
	@[ -d examples ] && cp -R examples $(SHAREDIR)/examples || true
	@printf '%s\n' \
	    '#!/usr/bin/env bash' \
	    '# aeo wrapper — generated by aeo `make install`' \
	    'export AEO_HOME="$(SHAREDIR)"' \
	    'exec "$(SHAREDIR)/bin/aeo" "$$@"' \
	    > $(BINDIR)/aeo
	chmod +x $(BINDIR)/aeo
	@SRCH=$$( $(SRCHASH_CMD) ); \
	 GITD=$$(git describe --always --dirty 2>/dev/null || echo unknown); \
	 VER=$$( [ -f VERSION ] && tr -d '[:space:]' < VERSION || echo 0.0.0-dev+$$SRCH ); \
	 printf 'src %s\ncommit %s\ninstalled %s\ntoolchain %s\nversion %s\n' \
	    "$$SRCH" "$$GITD" "$$(date '+%Y-%m-%d %H:%M:%S')" "$$($(AETHER) --version 2>/dev/null | head -1)" "$$VER" \
	    > $(SHAREDIR)/AEO_STAMP; \
	 echo "installed:"; \
	 echo "  wrapper:  $(BINDIR)/aeo   (pins AEO_HOME=$(SHAREDIR))"; \
	 echo "  runtime:  $(SHAREDIR)/"; \
	 echo "  version:  aeo $$VER (git $$GITD)"; \
	 echo "  NOTE: aeo shells 'ae' at runtime — ensure the Aether toolchain is on PATH."

uninstall:
	rm -f $(BINDIR)/aeo
	rm -rf $(SHAREDIR)

clean:
	rm -f bin/aeo

# check-install — is the installed aeo current with this source tree? Compares
# the dev tree's source-content hash against the installed AEO_STAMP.
check-install:
	@if [ ! -f "$(SHAREDIR)/AEO_STAMP" ]; then \
	    echo "aeo: not installed at $(SHAREDIR) — run 'make install'"; \
	else \
	    dev=$$( $(SRCHASH_CMD) ); \
	    inst=$$(awk '$$1=="src"{print $$2}' "$(SHAREDIR)/AEO_STAMP"); \
	    if [ "$$dev" = "$$inst" ]; then \
	        echo "aeo: installed tree is current (src $$inst)"; \
	    else \
	        echo "aeo: installed tree is STALE — installed src $$inst, this tree $$dev — run 'make install'"; \
	    fi; \
	fi
